//VIDEO_BUILDER ACTIONS
export const INIT_VIDEOS = 'INIT_VIDEOS';
export const SET_VIDEOS = 'SET_VIDEOS';
export const FETCH_VIDEOS_FAILED = 'FETCH_VIDEOS_FAILED';
export const SET_CURRENT_VIDEO = 'SET_CURRENT_VIDEO';
export const FETCH_VIDEO_FILTER = 'FETCH_VIDEO_FILTER';

//APP ACTION
export const TOGGLE_LAYOUT_SCROLL = 'TOGGLE_LAYOUT_SCROLL';