//VIDEO_BUILDER ACTIONS
export const INIT_VIDEOS = 'INIT_VIDEOS';
export const SET_VIDEOS = 'SET_VIDEOS';
export const FETCH_VIDEOS_FAILED = 'FETCH_VIDEOS_FAILED';
export const SET_CURRENT_VIDEO = 'SET_CURRENT_VIDEO';
export const FETCH_VIDEO_FILTER = 'FETCH_VIDEO_FILTER';

//PAGINATION
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_REQUEST_SENT = 'SET_REQUEST_SENT';
export const SET_TOTAL_ITEMS = 'SET_TOTAL_ITEMS';
export const FLUSH_VIDEOS = 'FLUSH_VIDEOS';

//APP ACTION
export const TOGGLE_LAYOUT_SCROLL = 'TOGGLE_LAYOUT_SCROLL';

//AUTH
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';